spring:
  application:
    name: WebChatApplication

  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/chat_app_db}
    username: ${DATABASE_USERNAME:chatapp_user}
    password: ${DATABASE_PASSWORD:chatapp_password}
    driver-class-name: com.mysql.cj.jdbc.Driver  # Spring actually autoconfigure but better to mention here

    jpa:
      hibernate:
        ddl-auto: validate   # It will automatically add column in database when some (Just validate adn give mismatch log)
      show-sql: false   # Logging true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect   # Spring autoconfigure but  mentioning it optimize
          format_sql: false   # Logging output get formated pretty

  logging:
    level:
      com.learning.WebChatApplication: INFO
      org.hibernate.sql: WARN
      org.springframework.web.socket: DEBUG

  # check later How can you use JPA here
